/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: aispeech.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif
#include <assert.h>
#include "aispeech.pb-c.h"

#ifdef NDEBG
#endif

void   speech__request__options_entry__init
                     (Speech__Request__OptionsEntry         *message)
{
  static const Speech__Request__OptionsEntry init_value = SPEECH__REQUEST__OPTIONS_ENTRY__INIT;
  *message = init_value;
}
void   speech__request__init
                     (Speech__Request         *message)
{
  static const Speech__Request init_value = SPEECH__REQUEST__INIT;
  *message = init_value;
}
size_t speech__request__get_packed_size
                     (const Speech__Request *message)
{
  assert(message->base.descriptor == &speech__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__request__pack
                     (const Speech__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__request__pack_to_buffer
                     (const Speech__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Request *
       speech__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Request *)
     protobuf_c_message_unpack (&speech__request__descriptor,
                                allocator, len, data);
}
void   speech__request__free_unpacked
                     (Speech__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech__response__init
                     (Speech__Response         *message)
{
  static const Speech__Response init_value = SPEECH__RESPONSE__INIT;
  *message = init_value;
}
size_t speech__response__get_packed_size
                     (const Speech__Response *message)
{
  assert(message->base.descriptor == &speech__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__response__pack
                     (const Speech__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__response__pack_to_buffer
                     (const Speech__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Response *
       speech__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Response *)
     protobuf_c_message_unpack (&speech__response__descriptor,
                                allocator, len, data);
}
void   speech__response__free_unpacked
                     (Speech__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech__result__init
                     (Speech__Result         *message)
{
  static const Speech__Result init_value = SPEECH__RESULT__INIT;
  *message = init_value;
}
size_t speech__result__get_packed_size
                     (const Speech__Result *message)
{
  assert(message->base.descriptor == &speech__result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__result__pack
                     (const Speech__Result *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__result__pack_to_buffer
                     (const Speech__Result *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Result *
       speech__result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Result *)
     protobuf_c_message_unpack (&speech__result__descriptor,
                                allocator, len, data);
}
void   speech__result__free_unpacked
                     (Speech__Result *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech__nlu__init
                     (Speech__Nlu         *message)
{
  static const Speech__Nlu init_value = SPEECH__NLU__INIT;
  *message = init_value;
}
size_t speech__nlu__get_packed_size
                     (const Speech__Nlu *message)
{
  assert(message->base.descriptor == &speech__nlu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__nlu__pack
                     (const Speech__Nlu *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__nlu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__nlu__pack_to_buffer
                     (const Speech__Nlu *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__nlu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Nlu *
       speech__nlu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Nlu *)
     protobuf_c_message_unpack (&speech__nlu__descriptor,
                                allocator, len, data);
}
void   speech__nlu__free_unpacked
                     (Speech__Nlu *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__nlu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech__slot__init
                     (Speech__Slot         *message)
{
  static const Speech__Slot init_value = SPEECH__SLOT__INIT;
  *message = init_value;
}
size_t speech__slot__get_packed_size
                     (const Speech__Slot *message)
{
  assert(message->base.descriptor == &speech__slot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__slot__pack
                     (const Speech__Slot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__slot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__slot__pack_to_buffer
                     (const Speech__Slot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__slot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Slot *
       speech__slot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Slot *)
     protobuf_c_message_unpack (&speech__slot__descriptor,
                                allocator, len, data);
}
void   speech__slot__free_unpacked
                     (Speech__Slot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__slot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speech__skill__init
                     (Speech__Skill         *message)
{
  static const Speech__Skill init_value = SPEECH__SKILL__INIT;
  *message = init_value;
}
size_t speech__skill__get_packed_size
                     (const Speech__Skill *message)
{
  assert(message->base.descriptor == &speech__skill__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speech__skill__pack
                     (const Speech__Skill *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speech__skill__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speech__skill__pack_to_buffer
                     (const Speech__Skill *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speech__skill__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Speech__Skill *
       speech__skill__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Speech__Skill *)
     protobuf_c_message_unpack (&speech__skill__descriptor,
                                allocator, len, data);
}
void   speech__skill__free_unpacked
                     (Speech__Skill *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speech__skill__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor speech__request__options_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Request__OptionsEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Request__OptionsEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__request__options_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange speech__request__options_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor speech__request__options_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Request.OptionsEntry",
  "OptionsEntry",
  "Speech__Request__OptionsEntry",
  "speech",
  sizeof(Speech__Request__OptionsEntry),
  2,
  speech__request__options_entry__field_descriptors,
  speech__request__options_entry__field_indices_by_name,
  1,  speech__request__options_entry__number_ranges,
  (ProtobufCMessageInit) speech__request__options_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__request__field_descriptors[6] =
{
  {
    "requestId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Request, requestid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sessionId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Request, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Request, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "homeId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Speech__Request, homeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Speech__Request, block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "options",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Speech__Request, n_options),
    offsetof(Speech__Request, options),
    &speech__request__options_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__request__field_indices_by_name[] = {
  4,   /* field[4] = block */
  3,   /* field[3] = homeId */
  5,   /* field[5] = options */
  0,   /* field[0] = requestId */
  1,   /* field[1] = sessionId */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange speech__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor speech__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Request",
  "Request",
  "Speech__Request",
  "speech",
  sizeof(Speech__Request),
  6,
  speech__request__field_descriptors,
  speech__request__field_indices_by_name,
  1,  speech__request__number_ranges,
  (ProtobufCMessageInit) speech__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__response__field_descriptors[5] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Response, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Response, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Response, requestid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Speech__Response, data),
    &speech__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Speech__Response, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__response__field_indices_by_name[] = {
  0,   /* field[0] = code */
  3,   /* field[3] = data */
  4,   /* field[4] = end */
  1,   /* field[1] = message */
  2,   /* field[2] = requestId */
};
static const ProtobufCIntRange speech__response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor speech__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Response",
  "Response",
  "Speech__Response",
  "speech",
  sizeof(Speech__Response),
  5,
  speech__response__field_descriptors,
  speech__response__field_indices_by_name,
  2,  speech__response__number_ranges,
  (ProtobufCMessageInit) speech__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__result__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sessionId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keepSession",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, keepsession),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asr",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, asr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nlg",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, nlg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nlu",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, nlu),
    &speech__nlu__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skill",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Speech__Result, skill),
    &speech__skill__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__result__field_indices_by_name[] = {
  3,   /* field[3] = asr */
  5,   /* field[5] = block */
  2,   /* field[2] = keepSession */
  4,   /* field[4] = nlg */
  6,   /* field[6] = nlu */
  1,   /* field[1] = sessionId */
  7,   /* field[7] = skill */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange speech__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor speech__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Result",
  "Result",
  "Speech__Result",
  "speech",
  sizeof(Speech__Result),
  8,
  speech__result__field_descriptors,
  speech__result__field_indices_by_name,
  1,  speech__result__number_ranges,
  (ProtobufCMessageInit) speech__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__nlu__field_descriptors[3] =
{
  {
    "domain",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Nlu, domain),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intent",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Nlu, intent),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Speech__Nlu, n_slot),
    offsetof(Speech__Nlu, slot),
    &speech__slot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__nlu__field_indices_by_name[] = {
  0,   /* field[0] = domain */
  1,   /* field[1] = intent */
  2,   /* field[2] = slot */
};
static const ProtobufCIntRange speech__nlu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor speech__nlu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Nlu",
  "Nlu",
  "Speech__Nlu",
  "speech",
  sizeof(Speech__Nlu),
  3,
  speech__nlu__field_descriptors,
  speech__nlu__field_indices_by_name,
  1,  speech__nlu__number_ranges,
  (ProtobufCMessageInit) speech__nlu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__slot__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Slot, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Slot, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Slot, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__slot__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange speech__slot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor speech__slot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Slot",
  "Slot",
  "Speech__Slot",
  "speech",
  sizeof(Speech__Slot),
  3,
  speech__slot__field_descriptors,
  speech__slot__field_indices_by_name,
  1,  speech__slot__number_ranges,
  (ProtobufCMessageInit) speech__slot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speech__skill__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Skill, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Skill, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Speech__Skill, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speech__skill__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange speech__skill__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor speech__skill__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "speech.Skill",
  "Skill",
  "Speech__Skill",
  "speech",
  sizeof(Speech__Skill),
  3,
  speech__skill__field_descriptors,
  speech__skill__field_indices_by_name,
  1,  speech__skill__number_ranges,
  (ProtobufCMessageInit) speech__skill__init,
  NULL,NULL,NULL    /* reserved[123] */
};
